---
- hosts: izanami,izanagi,kage*,atlas*
  gather_facts: yes
  user: ansible
  become: true
  roles: 
    - maintenance

- hosts: ubnt-*
  gather_facts: yes
  user: ansible
  become: true
  roles:
    - common


