---
- hosts: izanami,izanagi 
  gather_facts: yes
  user: ansible
  become: true
  roles: 
    - maintenance

- hosts: ubnt-*
  gather_facts: yes
  user: ansible
  become: true
  roles:
    - container/podman


