---
- hosts: ubuntu
  gather_facts: yes
  user: ansible
  become: true
  roles: 
    - container/docker_install
    - server

- hosts: debian-12
  gather_facts: yes
  user: ansible
  become: true
  roles: 
    - container/podman


