- name: Install podman in debian
  tags: ["podman"]
  block:
  - name: Install podman
    ansible.builtin.apt:
      pkg:
        - podman
      state: latest
      update_cache: yes

  - name: Activate backport repo for debian
    ansible.builtin.apt_repository:
      repo: "deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main" 
      state: present

  - name: Install cockpit
    ansible.builtin.apt:
      pkg:
        - cockpit
        - cockpit-podman
      state: latest
      default-release: "{{ ansible_distribution_release }}-backports"
      update_cache: yes
  when: ansible_facts["distribution"] == "Debian"
