- name: Install podman in debian
  tags: ["podman"]
  block:
  - name: Install podman
    ansible.builtin.apt:
      pkg:
        - podman
      state: latest
      update_cache: yes

  - name: Activate backport repo for debian
    ansible.builtin.apt_repository:
      repo: "deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main" 
      state: present

  - name: Install cockpit
    ansible.builtin.apt:
      pkg:
        - cockpit
        - cockpit-podman
      state: latest
      default-release: "{{ ansible_distribution_release }}-backports"
      update_cache: yes
  when: ansible_facts["distribution"] == "Debian"

- name: Install Podman in Ubuntu
  tags: ["podman"]
  block:
  - name: Install dependencies
    ansible.builtin.apt:
      pkg:
        - ca-certificates
        - curl
        - gnupg
        - lsb-core
      state: present

  - name: "Create keyrings directory if it does not exists"
    ansible.builtin.file:
      path: /etc/apt/keyrings
      owner: root
      group: root
      mode: 0755
      state: directory

  - name: Get Release
    ansible.builtin.command: lsb_release -rs
    register: lsb_release
      
  - name: Get Arch
    ansible.builtin.command: dpkg --print-architecture
    register: arch

  - name: Add keys to keyring
    ansible.builtin.apt_key:
      url: https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_{{ lsb_release.stdout }}/Release.key
      keyring: /etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg
      state: present

  - name: Add Repository
    ansible.builtin.apt_repository:
      repo: "deb [arch={{ arch.stdout }} signed-by=/etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg] \
             https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_{{ lsb_release.stdout }}/ /" 
      filename: devel:kubic:libcontainers:unstable
      state: present

  - name: Install podman
    ansible.builtin.apt:
      pkg:
        - podman
        - podman-plugins
        - podman-docker
        - cockpit-podman
      state: latest
      update_cache: yes
  - name: Install Podman Compose
    ansible.builtin.pip:
      name: podman-compose
      executable: pip3
  - name: Install Cockpit UI
    ansible.builtin.apt:
      name: cockpit
      state: latest
      install_recommends: yes
  when: ansible_facts["distribution"] == "Ubuntu"

