---
- name: "Enable timer"
  ansible.builtin.service:
    name: ansible-pull.timer
    state: started
    enabled: yes
- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
