---
- name: Load sensitive data
  ansible.builtin.include_vars:
    file: defaults/vault.yaml
    name: vault
  no_log: true

- name: Copy Vault Password To Remote
  ansible.builtin.copy:
    content: "{{ vault.vault_password }}"
    dest: "/etc/vault"
    owner: root
    group: root
    mode: "0660"

- name: Create Ansible Cache Directory
  ansible.builtin.file:
    path: "/ansible"
    mode: "0775"
    state: directory

- name: Add User Tasks...
  ansible.builtin.include_tasks:
    file: users.yaml



- name: Run Fonts Task...
  ansible.builtin.include_tasks:
    file: fonts.yaml



