---


- name: Install Debian Packages
  ansible.builtin.apt:
    pkg:
      - sudo
      - flatpak
      - unzip
      - tar
    state: present
    update_cache: yes
  when: ansible_facts["os_family"] == "Debian"





