---

- name: "Creating Users"
  block:
  - name: Create User For This System
    ansible.builtin.user:
      name: "{{ vault.username }}" 
      comment: "Raise and Shine"
      append: true 
      groups: [ "sudo" ]
      shell: "/bin/bash"
      state: present

  - name: Copy ssh public key
    ansible.builtin.lineinfile:
      path: "/home/{{ vault.username }}/.ssh/authorized_keys"
      create: true
      state: present
      insertafter: EOF
      line: "{{ lookup ('file', '~/.ssh/{{ vault.username_ssh_key }}.pub') }}"
      owner: "{{ vault.username }}"
      group: "{{ vault.username }}"
      mode: 0600
    notify: Restart sshd

  - name: Check If User Changed Password
    ansible.builtin.stat:
      path: "/home/{{ vault.username }}/.passwd_changed"
    register: p

  - name: Enforce Password Change
    ansible.builtin.shell: "passwd -e {{ vault.username }}"
    when: not p.stat.exists

  - name: User password change file
    ansible.builtin.file:
      path: "/home/{{ vault.username }}/.passwd_changed"
      state: touch
      owner: "{{ vault.username }}"
      group: "{{ vault.username }}"
  when: vault.username is defined





